#!/bin/bash
#
# Felipe Reyes <freyes@tty.cl>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

which synclient > /dev/null

if [ "$?" != "0" ]; then
    echo "synclient not found" >&2
    exit 1
fi

function show_usage {
    echo "$0 <toggle|on|off>" >&2
    exit 1;
}

function touchpad_toggle {
    status=$(synclient -l | grep TouchpadOff | awk -F' ' '{printf("%s", $3);}')
    newstatus=0
    if [ "x$status" == "x1" ]; then
        newstatus=0
    else
        if [ "x$status" == "x0" ]; then
            newstatus=1
        fi;
    fi;

    synclient TouchpadOff=$newstatus
}

if [ "x$1" == "x" ]; then
    show_usage
fi

case "${1}" in
     "toggle")
        touchpad_toggle
        ;;
    "on")
        synclient TouchpadOff=0
        ;;
    "off")
        synclient TouchpadOff=1
        ;;
    *)
        show_usage
        ;;
esac
